/**
 * Cross-language verification tests.
 *
 * These tests use test vectors generated by the Haskell backend
 * (test/GenTestVectors.hs → web/src/crypto/test-vectors.json) to verify
 * that the TypeScript verification implementation produces identical results.
 *
 * If the Haskell algorithms change, regenerate vectors:
 *   docker compose run --rm --entrypoint cabal dev run gen-test-vectors \
 *     | tail -1 > web/src/crypto/test-vectors.json
 */

import { describe, it, expect } from 'vitest'
import { hexToBytes, bytesToHex } from './entropy'
import {
  sha256,
  hkdfSha256,
  bytesToBigInt,
  deriveUniformN,
  deriveNthN,
  combineEntropy,
  deriveCoinFlip,
  deriveChoice,
  deriveIntRange,
  deriveWeightedChoice,
  deriveShuffle,
  verifyOutcome,
} from './verification'
import type { EntropyInput } from './verification'
import vectors from './test-vectors.json'

describe('Cross-language verification (Haskell test vectors)', () => {

  describe('HKDF-SHA256', () => {
    it('produces correct output with "veritas-uniform" info label', async () => {
      const input = hexToBytes(vectors.hkdf.input)
      const info = new TextEncoder().encode('veritas-uniform')
      const output = await hkdfSha256(input, info)
      expect(bytesToHex(output)).toBe(vectors.hkdf.uniform_output)
    })

    it('produces correct output with "veritas-shuffle-0" info label', async () => {
      const input = hexToBytes(vectors.hkdf.input)
      const info = new TextEncoder().encode('veritas-shuffle-0')
      const output = await hkdfSha256(input, info)
      expect(bytesToHex(output)).toBe(vectors.hkdf.shuffle_0_output)
    })

    it('produces correct output with "veritas-shuffle-1" info label', async () => {
      const input = hexToBytes(vectors.hkdf.input)
      const info = new TextEncoder().encode('veritas-shuffle-1')
      const output = await hkdfSha256(input, info)
      expect(bytesToHex(output)).toBe(vectors.hkdf.shuffle_1_output)
    })

    it('produces correct output with "veritas-shuffle-10" (multi-digit index)', async () => {
      const input = hexToBytes(vectors.hkdf.input)
      const info = new TextEncoder().encode('veritas-shuffle-10')
      const output = await hkdfSha256(input, info)
      expect(bytesToHex(output)).toBe(vectors.hkdf.shuffle_10_output)
    })
  })

  describe('Entropy combination', () => {
    it('SHA-256 of concatenated inputs matches Haskell output', async () => {
      const input1 = hexToBytes(vectors.combine.inputs[0])
      const input2 = hexToBytes(vectors.combine.inputs[1])
      const concat = new Uint8Array(input1.length + input2.length)
      concat.set(input1, 0)
      concat.set(input2, input1.length)
      const hash = await sha256(concat)
      expect(bytesToHex(hash)).toBe(vectors.combine.combined)
    })
  })

  describe('CoinFlip derivation', () => {
    it('matches Haskell result', async () => {
      const result = await deriveCoinFlip(vectors.coinFlip.entropy)
      expect(result).toBe(vectors.coinFlip.result)
    })
  })

  describe('UniformChoice derivation', () => {
    it('matches Haskell result', async () => {
      const result = await deriveChoice(
        vectors.uniformChoice.entropy,
        vectors.uniformChoice.choices,
      )
      expect(result).toBe(vectors.uniformChoice.result)
    })
  })

  describe('IntRange derivation', () => {
    it('matches Haskell result', async () => {
      const result = await deriveIntRange(
        vectors.intRange.entropy,
        vectors.intRange.lo,
        vectors.intRange.hi,
      )
      expect(result).toBe(vectors.intRange.result)
    })
  })

  describe('WeightedChoice derivation', () => {
    it('matches Haskell result', async () => {
      const choices: [string, number][] = vectors.weightedChoice.choices.map(
        (c) => [c.label, c.weight],
      )
      const result = await deriveWeightedChoice(
        vectors.weightedChoice.entropy,
        choices,
      )
      expect(result).toBe(vectors.weightedChoice.result)
    })
  })

  describe('Shuffle derivation', () => {
    it('matches Haskell result', async () => {
      const result = await deriveShuffle(
        vectors.shuffle.entropy,
        vectors.shuffle.items,
      )
      expect(result).toEqual(vectors.shuffle.result)
    })
  })

  describe('Full pipeline with canonical sorting', () => {
    it('combines entropy in correct order and derives matching outcome', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      // Provide in reverse order to test that sorting works
      const reversed = [...inputs].reverse()

      const combined = await combineEntropy(reversed)
      expect(combined).toBe(vectors.fullPipeline.combined_entropy)

      const coinResult = await deriveCoinFlip(combined)
      expect(coinResult).toBe(vectors.fullPipeline.coin_flip_result)
    })
  })

  describe('Mixed source types with cross-type priority sorting', () => {
    it('sorts ParticipantEntropy before DefaultEntropy before BeaconEntropy before VRFEntropy', async () => {
      // Contributions are provided in reverse canonical order (VRF, Beacon, Default, Participant)
      const inputs: EntropyInput[] = vectors.mixedSources.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.source_id,
          valueHex: c.value,
        }),
      )

      const combined = await combineEntropy(inputs)
      expect(combined).toBe(vectors.mixedSources.combined_entropy)
    })

    it('derives correct UniformChoice with mixed source types', async () => {
      const result = await deriveChoice(
        vectors.mixedSources.combined_entropy,
        vectors.mixedSources.choices,
      )
      expect(result).toBe(vectors.mixedSources.result)
    })
  })

  describe('verifyOutcome end-to-end', () => {
    it('verifies a CoinFlip ceremony', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'CoinFlip' },
        inputs,
        vectors.fullPipeline.combined_entropy,
        vectors.fullPipeline.coin_flip_result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('verifies a UniformChoice ceremony', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'UniformChoice', contents: vectors.uniformChoice.choices },
        inputs,
        vectors.fullPipeline.combined_entropy,
        vectors.uniformChoice.result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('verifies an IntRange ceremony', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'IntRange', contents: [vectors.intRange.lo, vectors.intRange.hi] },
        inputs,
        vectors.fullPipeline.combined_entropy,
        vectors.intRange.result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('verifies a WeightedChoice ceremony', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )
      const choices: [string, number][] = vectors.weightedChoice.choices.map(
        (c) => [c.label, c.weight],
      )

      const result = await verifyOutcome(
        { tag: 'WeightedChoice', contents: choices },
        inputs,
        vectors.fullPipeline.combined_entropy,
        vectors.weightedChoice.result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('verifies a Shuffle ceremony', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'Shuffle', contents: vectors.shuffle.items },
        inputs,
        vectors.fullPipeline.combined_entropy,
        vectors.shuffle.result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('verifies a mixed-source UniformChoice ceremony end-to-end', async () => {
      const inputs: EntropyInput[] = vectors.mixedSources.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.source_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'UniformChoice', contents: vectors.mixedSources.choices },
        inputs,
        vectors.mixedSources.combined_entropy,
        vectors.mixedSources.result,
      )

      expect(result.combinedEntropyMatch).toBe(true)
      expect(result.outcomeMatch).toBe(true)
    })

    it('detects mismatched combined entropy', async () => {
      const inputs: EntropyInput[] = vectors.fullPipeline.contributions.map(
        (c) => ({
          sourceType: c.source as EntropyInput['sourceType'],
          sourceId: c.participant_id,
          valueHex: c.value,
        }),
      )

      const result = await verifyOutcome(
        { tag: 'CoinFlip' },
        inputs,
        'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef',
        vectors.fullPipeline.coin_flip_result,
      )

      expect(result.combinedEntropyMatch).toBe(false)
    })
  })
})
